blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import IndexView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('main/', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from main.apps import MainConfig
from django.urls import path

from main.views import SubscriptionCreateView, SubscriptionDeleteView, SubscriptionListView, CancelView, SuccessView, \
    CreateCheckoutSessionView

app_name = MainConfig.name

urlpatterns = [
    path('subscription-create/<slug:slug>/', SubscriptionCreateView.as_view(), name='subscription_create'),
    path('subscription-cancel/<slug:slug>/', SubscriptionDeleteView.as_view(), name='subscription_delete'),
    path('subscription-list/', SubscriptionListView.as_view(), name='subscription_list'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/<slug:slug>/', SuccessView.as_view(), name='success'),
    path('create-checkout-session/<slug:slug>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from transliterate import translit
from django.utils.text import slugify

from users.models import User, NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=150, verbose_name='URL', unique=True)
    description = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', verbose_name='Изображение', **NULLABLE)
    date_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_publication = models.BooleanField(default=True, verbose_name='Признак публикации')
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', **NULLABLE)
    payment_amount = models.IntegerField(default=0, verbose_name='Стоимость подписки')
    is_paid = models.BooleanField(default=False, verbose_name='Контент платный')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """Преобразование заголовка в slug"""
        if not self.slug:
            # Транслитерация заголовка статьи с русского на английский
            title_translate = translit(self.title, 'ru', reversed=True)
            self.slug = slugify(title_translate, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'preview',
                  'is_publication', 'payment_amount', 'is_paid']
        exclude = ('slug', 'count_views', 'user')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog
from main.models import Subscription


class IndexView(TemplateView):
    extra_context = {
        'title': 'Главная страница'
    }
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog_list'] = Blog.objects.filter(is_publication=True).order_by('?')[:3]
        return context_data


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Статьи'
    }
    template_name = 'blog_list.html'

    def get_queryset(self):

        user = self.request.user
        subscription_blogs_id = Subscription.objects.filter(user=user, status=True).values_list('blog__id', flat=True)
        unsubscription_blogs = Blog.objects.filter(is_publication=True).exclude(id__in=subscription_blogs_id).exclude(user=user)

        return unsubscription_blogs


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
        return super().form_valid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return context_data

    def get_object(self, **kwargs):
        views = super().get_object(**kwargs)
        views.count_views += 1
        views.save()
        return views


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_detail', kwargs={'slug': self.object.slug})


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>


{% include 'blog/includes/inc_main_menu.html' %}

<div class="container">
    <div class="row mb-2">
        {% block content %}
        {% endblock %}
    </div>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card text-center">
                <form method="post">
                    {% csrf_token %}
                    Уверены, что хотите удалить?
                    <p>
                    <input type="submit" class="btn btn-danger btn-sm" value="Удалить">
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-success btn-sm">Отмена</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load mediapath %}
{% block content %}
<div class="cool">
    <div class="card">
        <div class="card-body">
            <img src="{% mediapath object.preview %}" style="max-width: 20%;" alt="Image">
            <table class="table">
                <tr>
                    <td>Заголовок</td>
                    <td>{{ object.title }}</td>
                </tr>
                <tr>
                    <td>Содержание</td>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td>{{ object.date_creation }}</td>
                </tr>
                <tr>
                    <td>Количество просмотров</td>
                    <td>{{ object.count_views }}</td>
                </tr>
            </table>
        </div>
        <div class="card-body d-flex flex-column align-items-start">
            {% if object.user == user or object.is_superuser %}
            <a class="alert-danger" href="{% url 'blog:blog_update' object.pk %}">>>Изменить</a>
            <a class="alert-warning" href="{% url 'blog:blog_delete' object.pk %}">>>Удалить</a>
            {% endif %}
        </div>
        <div class="card-footer">
            <a href="{% url 'main:subscription_list' %}" class="btn btn-primary"><< Назад</a>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">« Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load mediapath %}
{% block content %}
<div class="container">
    <a href="{% url 'blog:blog_create' %}" class="btn btn-primary">Создать статью</a>
</div>
{% for object in object_list %}
<div class="col-lg-12">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">{{ object.title }}</strong>
            <div class="mb-1 text-muted">{{ object.date_creation }}</div>
            <p class="card-text mb-auto">{{ object.description| truncatechars:100 }}</p>
            <ol class="list-group">Количество просмотров: {{ object.count_views }}</ol>
             <p class="card-text text-center">
                {% if user.is_authenticated %}
                    {% if object.is_paid or object.payment_amount > 0 %}
                        <form class="text-center" action="{% url 'main:create-checkout-session' slug=object.slug %}" method="post">
                            {% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Купить подписку за {{ object.payment_amount }} $">
                        </form>
                    {% else %}
                    <button type="button" class="btn btn-success">
                        <a href="{% url 'main:subscription_create' object.slug %}" class="text-white">Подписаться бесплатно</a>
                    </button>
                    {% endif %}
                {% endif %}
            </p>
        </div>
        <img src="{% mediapath object.preview %}" style="max-width: 30%;" alt="Image">
    </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load mediapath %}
{% block content %}

{% for object in blog_list %}
<div class="col-lg-12">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">{{ object.title }}</strong>
            <div class="mb-1 text-muted">{{ object.date_creation }}</div>
            <p class="card-text mb-auto">{{ object.description| truncatechars:100 }}</p>
            <ol class="list-group">Количество просмотров: {{ object.count_views }}</ol>
            <p class="card-text mb-auto">Дата создания статьи: {{ object.date_creation }}</p>
        </div>
        <img src="{% mediapath object.preview %}" style="max-width: 30%;" alt="Image">
    </div>
</div>
{% endfor %}
{% endblock %}