blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import IndexView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('main/', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, CustomPasswordResetView, CustomPasswordResetConfirmView, \
    CustomPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, phone, password, **extra_fields):
        """
            Создает и сохраняет пользователя с указанным номером телефона и паролем.
        """
        if not phone:
            raise ValueError("The given phone number must be set")
        user = self.model(phone=phone, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone=None, password=None, **extra_fields):
        """
            Создает и сохраняет суперпользователя с указанным номером телефона и паролем.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(phone, password, **extra_fields)


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True, **NULLABLE, verbose_name='Никнейм')
    phone = models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'{self.username} - {self.phone}'

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordResetForm, SetPasswordForm
from django import forms
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('phone', 'first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    phone = forms.CharField(
        max_length=20,
        required=True,
        label="Номер телефона",
        widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'}),
    )

    class Meta:
        model = User
        fields = ('phone', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.phone = self.cleaned_data["phone"]
        if commit:
            user.save()
        return user


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    email = forms.EmailField(
        widget=forms.HiddenInput(),
        required=False,
    )

    phone = forms.CharField(
        label=("Номер телефона"),
        max_length=254,
        widget=forms.TextInput(attrs={"autocomplete": "phone"}),
    )

    def save(self, request, **kwargs):
        phone = self.cleaned_data["phone"]
        user = User.objects.get(phone=phone)

        token_generator = kwargs.get('token_generator', default_token_generator)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = token_generator.make_token(user)

        return uid, token


class CustomResetConfirmForm(SetPasswordForm):
    class Meta:
        model = User

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView

from users.forms import UserForm, UserRegisterForm, CustomPasswordResetForm, CustomResetConfirmForm
from users.models import User


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm

    def form_valid(self, form):
        uid, token = form.save(self.request)
        return redirect('users:password_reset_confirm', uidb64=uid, token=token)


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomResetConfirmForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'

users/templates/users/login.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:password_reset' %}" class="btn btn-danger">Сгенерировать пароль</a>
        </div>
        <div class="card-footer"></div>
    </div>
    </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div style="display: flex; flex-direction: column; align-items: center; margin: 0 auto;"><h2 class="active">Пароль успешно изменен</h2>
        <a href="{% url 'users:login' %}" class="btn btn-link">
            Войти заново
        </a>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card text-center" style="width: 300px;">
            <div class="card-header h5 text-white bg-primary">Новый пароль</div>
            <div class="card-body px-5">
                <form method="post">
                    {% csrf_token %}
                    <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
                    <div class="form-group text-center">
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    <div class="form-group text-center">
                        <a href="{% url 'users:profile' %}" class="btn btn-primary">« Назад</a>
                    </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card text-center" style="width: 300px;">
            <div class="card-header h5 text-white bg-primary">Сброс пароля</div>
            <div class="card-body px-5">
                <form method="post" action="{% url 'users:password_reset' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                        <button class="btn btn-primary w-100">Сбросить пароль</button>
                    </div>
                </form>
            </div>
            <div class="form-group text-center">
                <a class="btn btn-outline-dark" href="{% url 'users:profile' %}">Назад</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:index' %}" class="btn btn-primary">« Назад</a>
            </div>
        </div>
    </div>

{% endblock %}