blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import IndexView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('main/', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from main.apps import MainConfig
from django.urls import path

from main.views import SubscriptionCreateView, SubscriptionDeleteView, SubscriptionListView, CancelView, SuccessView, \
    CreateCheckoutSessionView

app_name = MainConfig.name

urlpatterns = [
    path('subscription-create/<slug:slug>/', SubscriptionCreateView.as_view(), name='subscription_create'),
    path('subscription-cancel/<slug:slug>/', SubscriptionDeleteView.as_view(), name='subscription_delete'),
    path('subscription-list/', SubscriptionListView.as_view(), name='subscription_list'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/<slug:slug>/', SuccessView.as_view(), name='success'),
    path('create-checkout-session/<slug:slug>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
]

main/models.py
from django.db import models

from blog.models import Blog
from users.models import User, NULLABLE


class Subscription(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Контент')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    status = models.BooleanField(default=False, verbose_name='Статус подписки')
    payment_status = models.BooleanField(default=False, verbose_name='Статус оплаты')
    payment_date = models.DateField(verbose_name='Дата оплаты', **NULLABLE)

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user} - {self.blog}'

main/forms.py
from django.utils import timezone

from main.models import Subscription
from users.forms import StyleFormMixin
from django import forms


class SubscriptionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Subscription
        fields = []

    def create_subscription(self, user, blog):
        subscription = self.save(commit=False)
        subscription.user = user
        subscription.blog = blog
        subscription.status = True
        subscription.payment_status = True
        subscription.payment_date = timezone.now()
        subscription.save()

main/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
import stripe
from django.views.generic import TemplateView, CreateView, ListView, DeleteView

from blog.models import Blog
from main.forms import SubscriptionForm
from main.models import Subscription

stripe.api_key = settings.STRIPE_SECRET_KEY
DOMAIN = "http://127.0.0.1:8000"


class CreateCheckoutSessionView(View):

    def post(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, slug=self.kwargs['slug'])

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'usd',
                        'unit_amount': blog.payment_amount * 100,
                        'product_data': {
                            'name': blog.title,
                        },
                    },
                    'quantity': 1,
                },
            ],
            mode='payment',
            success_url=DOMAIN + reverse('main:success', kwargs={'slug': blog.slug}),
            cancel_url=DOMAIN + reverse('main:cancel')
        )

        return redirect(checkout_session.url, code=303)


class CancelView(TemplateView):
    template_name = 'main/cancel.html'


class SuccessView(TemplateView):
    template_name = 'main/success.html'

    def get(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, slug=self.kwargs['slug'])
        user = self.request.user

        Subscription.objects.create(
            user=user,
            blog=blog,
            status=True,
            payment_status=True,
            payment_date=timezone.now()
        )
        return render(request, 'main/success.html')


class SubscriptionCreateView(CreateView):
    model = Subscription
    template_name = 'main/subscription_form.html'
    success_url = reverse_lazy('blog:blog_list')
    form_class = SubscriptionForm

    def form_valid(self, form):
        blog = get_object_or_404(Blog, slug=self.kwargs['slug'])
        form.create_subscription(self.request.user, blog)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = get_object_or_404(Blog, slug=self.kwargs['slug'])
        context['blog'] = blog
        return context


class SubscriptionListView(ListView):
    model = Subscription
    template_name = 'main/subscription_list.html'

    def get_queryset(self):
        user = self.request.user

        subscription_blogs_id = Subscription.objects.filter(user=user, status=True).values_list('blog__id', flat=True)
        subscription_blogs = Blog.objects.filter(id__in=subscription_blogs_id, is_publication=True)
        user_blog_publication = Blog.objects.filter(user=user, is_publication=True)
        user_blog_unpublication = Blog.objects.filter(user=user, is_publication=False)
        data = (subscription_blogs | user_blog_publication | user_blog_unpublication).distinct()

        return data


class SubscriptionDeleteView(DeleteView):
    model = Subscription
    template_name = 'main/subscription_confirm_delete.html'
    success_url = reverse_lazy('main:subscription_list')

    def get_queryset(self):
        return Subscription.objects.filter(user=self.request.user)

    def get_object(self, queryset=None):
        return get_object_or_404(self.get_queryset(), blog__slug=self.kwargs['slug'])

main/templates/main/cancel.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-header text-center">
            <div class="bg-light p-5 rounded mt-3">
                <h1>Приходите оплатить в следующий раз!</h1>
            </div>
            <div class="form-group text-center">
                <a class="btn btn-success mt-3" href="{% url 'blog:blog_list' %}"><< Назад</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/subscription_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header text-center">
            <div class="bg-light p-5 rounded mt-3">
                <h1>Уверены, что хотите удалить подписку?</h1>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group text-center">
                        <button class="btn btn-danger mt-3" type="submit">Удалить</button>
                        <a href="{% url 'main:subscription_list' %}"
                           class="btn btn-success mt-3">Отменить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/subscription_form.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header text-center">
            <div class="bg-light p-5 rounded mt-3">
                <h1>Подписка на блог:</h1>
                <p class="lead">{{ blog.title }}</p>
            </div>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group text-center">
                    <button class="btn btn-success mt-3" type="submit">Подписаться</button>
                    <a href="{% url 'blog:blog_list' %}"
                       class="btn btn-warning mt-3">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/subscription_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% load mediapath %}

{% for object in object_list %}
{% if object.is_publication or object.user == user %}
<div class="col-lg-12">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">{{ object.title }}</strong>
            <div class="mb-1 text-muted">{{ object.date_creation }}</div>
            <p class="card-text mb-auto">{{ object.description| truncatechars:100 }}</p>
            <ol class="list-group">Количество просмотров: {{ object.count_views }}</ol>
            <button type="button" class="btn btn-success">
                <a href="{% url 'blog:blog_detail' object.slug %}" class="text-white">Читать статью..</a>
            </button>
            {% if object.user != user %}
            <button type="button" class="btn btn-warning">
                <a href="{% url 'main:subscription_delete' object.slug %}" class="text-dark">Отменить подписку</a>
            </button>
            {% endif %}
        </div>
        <img src="{% mediapath object.preview %}" style="max-width: 30%;" alt="Image">
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

main/templates/main/success.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-header text-center">
            <div class="bg-light p-5 rounded mt-3">
                <h1>Спасибо, что оформили подписку!</h1>
            </div>
            <div class="form-group text-center">
                <a class="btn btn-success mt-3" href="{% url 'blog:blog_list' %}">Вернуться на главную</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}